#!/usr/bin/env bash

GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[1;33m"
RESET="\033[0m"

echo -e "${RED}Welcome to YT Extracter CLI!${RESET}"

choice=$(printf "Download Audio\nDownload Video\nnone" | fzf --prompt="Choose an option: " --layout=reverse)

if [[ "$choice" == "Download Audio" ]]; then
  read -p "Enter the name of the audio file: " response
  read -p "Enter video URL: " video
  echo -e "${GREEN}From URL to MP3 in seconds.${RESET}"
  yt-dlp -x --audio-format mp3 --force-overwrites -o "${response}.mp3" "$video"

elif [[ "$choice" == "Download Video" ]]; then
  read -p "Enter the name of the video file: " response
  read -p "Enter video URL: " video
  echo -e "${YELLOW}Downloading video...${RESET}"
  yt-dlp --force-overwrites -o "${response}" "$video"

else
  echo -e "${RED}Invalid operation!${RESET}"
fi
