#!/bin/bash

# Set the source directory (Downloads)
DOWNLOADS_DIR="$HOME/Downloads"

SELECTED_FILE=$(find "$DOWNLOADS_DIR" \( -type f -o -type d \) | fzf)

# Check if a file was selected
if [[ -n "$SELECTED_FILE" ]]; then
  rsync -avh --progress "$SELECTED_FILE" ./
  read -p "Would you like to delete the original file? (y/N): " res
  if [[ "$res" =~ ^[Yy]$ ]]; then
    rm -r "$SELECTED_FILE"
    echo "Original file deleted!"
  fi

  echo "Copied: $SELECTED_FILE to $(pwd)"
else
  echo "No file selected."
fi
