#!/bin/bash

GREEN="\033[0;32m"
RED="\033[0;31m"
YELLOW="\033[1;33m"
RESET="\033[0m"

echo -e "${GREEN}Download successful!${RESET}"
echo -e "${YELLOW}Processing...${RESET}"
echo -e "${RED}Something went wrong.${RESET}"
